name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12, 14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
        if: ${{ matrix.node >= 12 }}
      - name: Test
        run: UVU_SETTINGS="-r esm" yarn test
        if: ${{ matrix.node < 12 }}
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
        if: ${{ matrix.node == 14 }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
